//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int Id { get; set; }
        public int LocationId { get; set; }
        public string DayOfTheWeek { get; set; }
        public string Deal1 { get; set; }
        public string TimeConstraint { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
